id: P005585
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18709
  title: ཏང་དང་རྒྱལ་ཁབ་ཀྱི་མི་རིགས་སྲིད་ཇུས་དྲིལ་བསྒྲགས་སློབ་གསོའི་གནད་བསྡུས།
  author: ''
  volumes:
    0a08822762454ea286f1ff7b55f15271:
      image_group_id: I8LS18711
      title: ''
      volume_number: 1
      total_pages: 53
      base_file: v001.txt
